language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

sudo: required

before_install:
 - chmod +x gradlew

script:
   - ./gradlew build connectedCheck