sudo: false
language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.3
  - android-23
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  #- sys-img-armeabi-v7a-android-23
deploy:
- provider: releases
  api_key:
    secure: "wJfZzD8JmtnmodRgi3AKEVvwND4qbpwfdMeK0E/uRAEeGRw2QsFcOGTDor0km3e8Y4lWt0z+ON1IwerHUK1EsqhyvJO5mdrfyFhA7Brc2Hr5/Pw+RMez+LL+aYMJGY6af34GywPpEY4fXWYuRM5QIeKpizM45Z0lMh8SU3ZZcB9VBwkZmDWNGzlbqZsWt7KQvhwz4MrHhUVhpoC3uZzWIN7IHBn+TMDGXQsmGFRQmbN5TvVvjrhWf+cf1G/dZzG/cEsEcWly8HJekNIlB0VuF+d0nngGXBt9kZhu0r/HDSmThAC8/5z58l0poi9pEbr//bx9czoziippWT/gRyHWkEo9PaxmOPjhjbmhMZD+G/1fYBNUXHNZRuISQNfOvicvCSNRnnPjXzxaF2BluyA139hxZefcxvj07ab9coqqZ8O22qt7UhY8mqih886T8oasQqov+ykeHg96swPdpVUeQ66CMh87mW4KVaB5JvjKgpLuoUpCDSOBffiU4A3HIJZcPew+iEczGDA9w5ZpwvWluDJajFMpt++QesmN007VpKRxaj2Kxr8XfP8/hvfK1rqv6HAtKWweIkjXNeMhKwkUKhRG09Ojc4JpaZehrBQgkxYQuD1hWYoc+U7QJC9wguSxYOLTO93YjRq2i47fRozyQO1Cjsu3o1HQAQQHieInlUI="
  file: app/build/outputs/apk/app-release-unsigned.apk
  skip_cleanup: true
  on:
    repo: NerdCats/RoboCat
    tags: true
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
  - secure: "wJfZzD8JmtnmodRgi3AKEVvwND4qbpwfdMeK0E/uRAEeGRw2QsFcOGTDor0km3e8Y4lWt0z+ON1IwerHUK1EsqhyvJO5mdrfyFhA7Brc2Hr5/Pw+RMez+LL+aYMJGY6af34GywPpEY4fXWYuRM5QIeKpizM45Z0lMh8SU3ZZcB9VBwkZmDWNGzlbqZsWt7KQvhwz4MrHhUVhpoC3uZzWIN7IHBn+TMDGXQsmGFRQmbN5TvVvjrhWf+cf1G/dZzG/cEsEcWly8HJekNIlB0VuF+d0nngGXBt9kZhu0r/HDSmThAC8/5z58l0poi9pEbr//bx9czoziippWT/gRyHWkEo9PaxmOPjhjbmhMZD+G/1fYBNUXHNZRuISQNfOvicvCSNRnnPjXzxaF2BluyA139hxZefcxvj07ab9coqqZ8O22qt7UhY8mqih886T8oasQqov+ykeHg96swPdpVUeQ66CMh87mW4KVaB5JvjKgpLuoUpCDSOBffiU4A3HIJZcPew+iEczGDA9w5ZpwvWluDJajFMpt++QesmN007VpKRxaj2Kxr8XfP8/hvfK1rqv6HAtKWweIkjXNeMhKwkUKhRG09Ojc4JpaZehrBQgkxYQuD1hWYoc+U7QJC9wguSxYOLTO93YjRq2i47fRozyQO1Cjsu3o1HQAQQHieInlUI="
before_script:
#- echo no | android create avd --force --name test --target android-23 --abi armeabi-v7a
#- emulator -avd test -no-skin -no-audio -no-window -gpu off -no-boot-anim &
#- android-wait-for-emulator
#- adb devices
#- adb shell input keyevent 82 &
before_install:
- chmod +x gradlew
script:
#- echo $ADB_INSTALL_TIMEOUT
#- android list target
- "./gradlew assemble"
